### ISSUE TITLE
Design updates task tracker

### ISSUE THREAD

**Issue by cgalbiati** [melforprogress/melforprogress.com#26]
Design updates:

Shared design elements:
- [ ] more link
- update headers and content styling

Tasks:
- [ ] hero with image and action network sign up
	- [ ] sign up design
	- [ ] image sizing/scaling etc with placeholder sign up (@cgalbiati)
- [ ] Policy
    - [ ] collapsing for mobile
    - [ ] image/text layout
- [ ]  control shift integration (gary)
- [ ] Actblue with prefill
- [ ] press 
- [ ] register to vote button
- [ ] paid for module in footer
- [ ] social on nav

**Comment by cgalbiati** [comment]
[Gagarin-website-20190904.pdf](https://github.com/melforprogress/melforprogress.com/files/3684114/Gagarin-website-20190904.pdf)
